name=Grove - 125KHz RFID Reader (14 bytes)
version=2.0.0
author=Ye Xiaobo from Seeed Studio <yexiaobo@seeedstudio.com>, Adrien FALLOT <dev@adrienfallot.fr>
maintainer=Adrien FALLOT <dev@adrienfallot.fr>
sentence=Arduino library to control Grove - 125KHz RFID Reader.
paragraph=This revised version now decodes cards (or badges) that transmit 14 bytes, whereas the previous version handled only 5 bytes.
category=Communication
url=https://github.com/adrienfallot/RFID_Library
architectures=*